name: fuild file

on:
  push:
    branches:
      - 'fork-master'


jobs:
 build_golang:
   runs-on: ubuntu-latest
   strategy:
     matrix:
       go-version: [ '1.19' ]
       os: [ 'windows-latest', 'ubuntu-latest', 'macos-latest' ]
   steps:
     - name: Checkout code
       uses: actions/checkout@v3
     - name: Set up Go
       uses: actions/setup-go@v4
       with:
         go-version: ${{ matrix.go-version }}

     - name: Build
       run: |
         GOOS=windows GOARCH=amd64 go build -o myapp-windows-amd64.exe
         GOOS=linux GOARCH=amd64 go build -o myapp-linux-amd64
         GOOS=darwin GOARCH=amd64 go build -o myapp-macos-amd64

     - name: Upload Windows Artifacts
       uses: actions/upload-artifact@v3
       with:
         name: myapp-windows-amd64.exe
         path: |
           myapp-windows-amd64.exe

     - name: Upload Linux Artifacts
       uses: actions/upload-artifact@v3
       with:
         name: myapp-linux-amd64
         path: |
           myapp-linux-amd64

     - name: Upload Linux Artifacts
       uses: actions/upload-artifact@v3
       with:
         name: myapp-macos-amd64
         path: |
           myapp-macos-amd64